GROUP_ID=io.github.codandotv
POM_NAME=popcornguineapig-detekt-rule
POM_DESCRIPTION=Small popcornguineapig set of detekt rules to check for architecture violation
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/CodandoTV/popcornguineapig-detekt-rule
ARTIFACT_ID=popcornguineapig-detekt-rule

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit

POM_DEVELOPER_ID=CodandoTV
POM_DEVELOPER_NAME=CodandoTV
POM_DEVELOPER_URL=https://github.com/CodandoTV/
POM_DEVELOPER_EMAIL=codando.tv@gmail.com